### ISSUE TITLE
Cannot write gpt partitions to disk

### ISSUE THREAD

**Issue by fengz63** [rust-disk-partition-management/gptman#110]
Hi, I have a question about how to write gpt partitions to local disk. The code is as follows
```rust
fn create_disk() -> Result<(), ()> {
    let mut f = OpenOptions::new()
        .read(true)
        .write(true)
        .open("test.img")
        .unwrap();

    let ss = 512;

    let mut gpt = gptman::GPT::new_from(&mut f, ss as u64, [0xff; 16])
        .expect("could not create GPT partitions");

    let free_partition_number = gpt
        .iter()
        .find(|(_i, p)| p.is_unused())
        .map(|(i, _)| i)
        .expect("no more places available");

    println!("num: {}", free_partition_number);

    gpt[free_partition_number] = gptman::GPTPartitionEntry {
        partition_type_guid: [0xff; 16],
        unique_partition_guid: [0xfe; 16],
        starting_lba: 2048,
        ending_lba: 4095,
        attribute_bits: 0,
        partition_name: "A Robot Named Fight!".into(),
    };

    gpt.write_into(&mut f).unwrap();

    Ok(())
}
```
I use the same code in `mbrman` crate, then I could write mbr partitions successfully in `test.img`. However in `gptman` crate, it can't be writed in `test.img`.
Is there anyone known what mistake I have made?

**Comment by cecton** [comment]
Hello!

Does the `test.img` file exists and is non-empty? gptman needs to know the size of the disk because the GPT is written at the beginning AND at the end of the disk. (I think it's possible we don't handle 0 sized disk at the moment which is kind of a bug)

Do you have an error message btw?

**Comment by cecton** [comment]
The file needs to be at least 2065K I think for it to work

**Comment by fengz63** [comment]
The `test.img` exists, it is created by the `qemu-img`, and the size is `2G`.

**Comment by fengz63** [comment]
Oh, I have found that, after the `write_into()` function, I add the [write_protective_mbr_into](https://docs.rs/gptman/1.0.0/gptman/struct.GPT.html#method.write_protective_mbr_into) function, then I could write the gpt partitions into the `test.img`. However, I don't know why? Could anyone give me some advice?

**Comment by cecton** [comment]
Can you be more specific on what issue you have encountered exactly? Also the exact command you use with `qemu-img`.

**Comment by cecton** [comment]
Well I guess the issue you had was that you had 2 partition tables on the disk: a MBR one and a GPT one. This means a program can interpret one or the other as the source of truth.

We could change gptman to automatically write the protective MBR but I think this will look like a "side effect". My reasoning is that writing GPT should mean only writing GPT, not erasing some other partition table on the disk.

I'm closing this issue for now but anyone can re-open it to argue about this.
