### ISSUE TITLE
Consider increasing MSRV

### ISSUE THREAD

**Issue by bgilbert** [rust-disk-partition-management/gptman#119]
gptman's dependencies will continue to migrate to newer versions of Rust.  By now, applications that need to support old compilers will have much larger problems than the MSRV of gptman.  To reduce maintenance burden, can we consider increasing the MSRV and releasing version 1.1.0?

**Comment by cecton** [comment]
Yes maybe that's the easiest in the end. I just don't see how to maintain this without doing weird stuff everywhere

**Comment by cecton** [comment]
I had to do this to make it work in the CI: #112
