### ISSUE TITLE
Dropping the CLI

### ISSUE THREAD

**Issue by cecton** [rust-disk-partition-management/gptman#126]
I was thinking about removing the CLI entirely. It's a bit of maintenance and I doubt very much anybody uses it at all. I did it as a pet project back in the days to learn Rust. Nowadays I believe the lib is still actually used but not the CLI itself.

Since all the dependencies of the CLI are behind a feature flag, I think it can be easily removed without breaking compatiblity for anyone.

What do you think @bgilbert?

**Comment by bgilbert** [comment]
I'm okay with that, and it would simplify maintenance.  In principle the CLI could be useful for testing the library, but I've never used it that way.

**Comment by brandonros** [comment]
I just used the CLI haha not sure if that's me being weird. I'm on Mac trying to set up some random USB stick "the hard way".

I was going to say "resize" is kind of hard to use. I know it's very close to original fdisk but counting in sectors is a bit weird.

I also got confused on how to set the right type for "exFAT".

**Comment by cecton** [comment]
> I just used the CLI haha not sure if that's me being weird. I'm on Mac trying to set up some random USB stick "the hard way".

waaat! I can't believe someone is actually using it! haha Well thanks for that! :hearts: I actually forgot about that PR but I guess I will wait a bit longer in case I change my mind or move it to the examples or something... (or to another crate?)

> I was going to say "resize" is kind of hard to use. I know it's very close to original fdisk but counting in sectors is a bit weird

I just tested and you can actually use `MB` (or GB, etc... it even handles MIB, GIB, ... (powers of 1024)) to give a size in megabytes. This could be indicated better though! It is well indicated when you create a new partition but not when you resize.

:warning:  btw if you are learning on this thing watch out because these tools (fdisk, parted, gptman, etc...) don't handle the filesystems! If you shrink a partition, you first need to use another tool to shrink the filesystem and then a partition manager to actually shrink the partition.

In the past, parted would call the appropriate program to do the resize for you but they removed that at some point. GParted on the other hand still does the filesystem resizing for you.

Same issue when you move a partition around. Tools that are for managing the filesystem won't copy the data itself.

> I also got confused on how to set the right type for "exFAT". I was going to ask for help on how to do that here.

It's probably the `Microsoft basic data` type partition (EBD0A0A2-B9E5-4433-87C0-68B6B72699C7). In GUID partition tables the "type" of the partition does not give the filesystem type. I guess it's only used to tell the system how to handle it (ignore it, hide it, mount it, etc...) and what filesystems to expect (Linux filesystem data can hold any type really).

**Comment by cecton** [comment]
(And you need to format the partition yourself after creating it. So you create a Microsoft basic data partition and you use mkfs.exfat on it (not sure if it's the same tool on Mac). Make sure the OS actually refreshes the partition after you updated the partition table)

**Comment by brandonros** [comment]
Another interesting use case maybe:

```
$ gptman ~/Downloads/debian-12-nocloud-amd64.raw 
Command (m for help): p
Sector size: 512 bytes
Partition alignment: 2048 (1048576 bytes)
Disk size: 2.15 GB (2147483648 bytes)
Usable sectors: 2048-4194270 (4192223 sectors)
Free sectors: 4192256-4194270 (1.03 MB)
Usable space: 2.15 GB (2146418176 bytes)
Disk identifier: 64143264-D9C2-BE46-AAB1-514611F2346B

Device                                                   Start      End  Sectors       Size  Type                           GUID                                  Attributes  Name
/Users/brandon/Downloads/debian-12-nocloud-amd64.raw1   262144  4192255  3930112    2.01 GB  Linux / Linux filesystem data  0AA74844-EDE7-564F-9DA4-3299E6CD9F95                  
/Users/brandon/Downloads/debian-12-nocloud-amd64.raw14    2048     8191     6144    3.15 MB  _ / BIOS boot partition        6AC66D8A-0123-4946-9803-BB807C1C4EC2                  
/Users/brandon/Downloads/debian-12-nocloud-amd64.raw15    8192   262143   253952  130.02 MB  _ / EFI System partition       F080A98F-3C34-D44C-B995-D9B1C2365E3D 
```

Being able to extract from a `.raw` into the partition represented (individual files). I believe on Linux you can `mount` as `loop` or something. Not sure what options are in Mac/userspace...

Otherwise as I understand it, if you write this 2GB raw file to a 32GB USB stick, you end up with 30GB unused so you have to resize the partition table and the underlying partition.

**Comment by cecton** [comment]
> Edit 2: I probably overcomplicated this/was being stubborn. `brew install qemu && sudo qemu-system-x86_64 -boot d -drive file=/dev/rdisk4,format=raw -m 2048 -cdrom /Users/brandon/Downloads/debian-12.4.0-amd64-netinst.iso` was "good enough" for what I wanted to jump start a USB stick

oh yes that's an excellent idea and probably the easiest if you don't need hardware acceleration or anything



> Edit: `hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount ~/Downloads/debian-12-nocloud-amd64.raw` seems to work pretty well on Mac OS X.

good to know the command, thanks! Maybe something I could add in the doc somewhere



> Being able to extract from a `.raw` into the partition represented (individual files).

I think it might be out of scope with a partition manager BUT to be honest I was interested to go a bit beyond the scope. For example I remember I added very later a command to check if a partition only has zeroes (command z in the cli). It's mostly useful for SSDs. I also wanted to integrate [ddssd](https://gitlab.com/cecton/ddssd) into the cli (which also operates on the content of the partition itself) (that one is a tool that basically does dd if=... of=... with the caveat that it skips sectors that are empty (they are not written to the destination).

**Comment by brandonros** [comment]
```shell
$ dd if=/dev/zero of=file.raw bs=1M count=2048
$ gptman file.raw
invalid signature
```

is there a way to jumpstart an empty file with a GPT that I'm not thinking of?

**Comment by brandonros** [comment]
@cecton I have an interesting one that is 100% unrelated to this project but also slightly maybe related.

```
$ gdisk file.raw 
GPT fdisk (gdisk) version 1.0.9

Warning! Disk size is smaller than the main header indicates! Loading
secondary header from the last sector of the disk! You should use 'v' to
verify disk integrity, and perhaps options on the experts' menu to repair
the disk.
Caution: invalid backup GPT header, but valid main header; regenerating
backup header from main header.

Warning! Error 25 reading partition table for CRC check!
Warning! One or more CRCs don't match. You should repair the disk!
Main header: OK
Backup header: ERROR
Main partition table: OK
Backup partition table: ERROR

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: damaged

****************************************************************************
Caution: Found protective or hybrid MBR and corrupt GPT. Using GPT, but disk
verification and recovery are STRONGLY recommended.
****************************************************************************
```

```shell
#!/bin/bash

set -e

install_prerequisites() {
    brew install dosfstools e2fsprogs
}

create_drive_file() {
    dd if=/dev/zero of=file.raw bs=1M count=2048
}

partition_drive_file() {
    #gdisk file.raw
    gptman -i file.raw
    # new 500mb partition of type 1 -> 2 (EFI System partition,  C12A7328-F81F-11D2-BA4B-00A0C93EC93B, ef00)
    # new partition of type 12 -> 14 (Root partition, x86-64, 4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709, 8304)
}

extract_partitions() {
    header_start_sector=0
    header_end_sector=2047
    header_num_sectors=$((header_end_sector - header_start_sector + 1))
    efi_start_sector=2048
    efi_end_sector=978943
    efi_num_sectors=$((efi_end_sector - efi_start_sector + 1))
    root_start_sector=978944
    root_end_sector=4192255
    root_num_sectors=$((root_end_sector - root_start_sector + 1))
    dd if=file.raw of=gpt_header.img bs=512 count=$header_num_sectors skip=$header_start_sector
    dd if=file.raw of=fat32_partition.img bs=512 count=$efi_num_sectors skip=$efi_start_sector
    dd if=file.raw of=ext4_partition.img bs=512 count=$root_num_sectors skip=$root_start_sector
    rm file.raw
}

format_partitions() {
    mkfs.fat -F32 -n 'EFI' fat32_partition.img
    mkfs.ext4 ext4_partition.img
}

mount_partitions() {
    mkdir -p ~/Desktop/ext4
    mkdir -p ~/Desktop/fat32
    hdiutil attach -imagekey diskimage-class=CRawDiskImage -nomount fat32_partition.img
    sudo mount -t msdos /dev/disk5 ~/Desktop/fat32
    ext4fuse ext4_partition.img ~/Desktop/ext4
}

unmount_partitions() {
    sudo umount ~/Desktop/fat32
    sudo umount ~/Desktop/ext4
    hdiutil detach /dev/disk5
}

prepare_efi_partition() {
    mkdir -p ~/Desktop/fat32/EFI/BOOT
    cp ~/Downloads/refind-bin-0.14.0.2/refind/refind_x64.efi ~/Desktop/fat32/EFI/BOOT/bootx64.efi
    cp ~/Downloads/debian-live-12.4.0-amd64-standard/live/vmlinuz ~/Desktop/fat32/EFI/BOOT/vmlinuz
    cp ~/Downloads/debian-live-12.4.0-amd64-standard/live/initrd.img ~/Desktop/fat32/EFI/BOOT/initrd.img
    cat <<EOF > ~/Desktop/fat32/EFI/BOOT/refind.conf
menuentry "Linux" {
    loader /EFI/BOOT/vmlinuz
    initrd /EFI/BOOT/initrd.img
    options "ro root=9F6A58FB-D338-DA3E-8CFC-94E069467731 console=ttyS0"
}
EOF
}

prepare_root_partition() {
    echo "TODO"
    # TODO: copy files to ~/Desktop/root
}

rebuild_drive_file() {
    cat gpt_header.img fat32_partition.img ext4_partition.img > file.raw
    rm gpt_header.img fat32_partition.img ext4_partition.img
}

run_qemu() {
    cp /opt/homebrew/Cellar/qemu/8.1.3_2/share/qemu/edk2-i386-vars.fd /opt/homebrew/Cellar/qemu/8.1.3_2/share/qemu/edk2-x86_64-vars.fd
    qemu-system-x86_64 \
        -drive if=pflash,format=raw,unit=0,readonly=on,file=/opt/homebrew/Cellar/qemu/8.1.3_2/share/qemu/edk2-x86_64-code.fd \
        -drive if=pflash,format=raw,unit=1,file=/opt/homebrew/Cellar/qemu/8.1.3_2/share/qemu/edk2-x86_64-vars.fd \
        -drive file=file.raw,format=raw \
        -m 2048 \
        -nographic
}

#install_prerequisites
create_drive_file
partition_drive_file
extract_partitions
format_partitions
mount_partitions
prepare_efi_partition
prepare_root_partition
unmount_partitions
rebuild_drive_file
run_qemu
```

How would you expect rebuilding a disk image into partition files and then back into a disk image to work/do you see the error/anything I'm doing wrong?
