### ISSUE TITLE
Release workflow broken

### ISSUE THREAD

**Issue by cecton** [rust-disk-partition-management/gptman#97]
https://github.com/rust-disk-partition-management/gptman/runs/6737705848?check_suite_focus=true

Release 1.0.0 failed for the following reason when creating the release:

> Error: Resource not accessible by integration

I guess it's related to a lack of permission.

@bgilbert you have played with this recently, maybe you know how to fix this? Unfortunately the release on crates.io is done so we don't want to touch the tag or the commit... :disappointed:

**Comment by bgilbert** [comment]
Oh, this is the same problem as https://github.com/rust-disk-partition-management/gptman/pull/92.  Let me try to figure out what permissions it needs.

**Comment by bgilbert** [comment]
Once this is fixed, I think we can push a hacked-up version of the workflow to a branch and manually run it from the branch, having it hardcode the existing tag to build.

**Comment by bgilbert** [comment]
Okay, I'm not sure if this is sufficient, but worth a shot: https://github.com/rust-disk-partition-management/gptman/compare/main...release  Want to look it over and then one of us can try running it from the branch?

**Comment by cecton** [comment]
Ok that sounds great

**Comment by bgilbert** [comment]
Because the `main` version of the workflow isn't configured to allow running it manually, we can't run it from a branch without https://github.com/rust-disk-partition-management/gptman/pull/98.  We can revert it afterward.

(An alternative is to just finish the release by hand, using the binaries already built by the failed run.  However, that wouldn't let us test the fix until the next release.)

**Comment by cecton** [comment]
Yes I thought of both too... there is no perfect solution.

If you're confident this will work I don't mind making the release manually and taking a leap of faith for the workflow. wdyt?

**Comment by bgilbert** [comment]
I'm not 100% confident.  The docs are a bit fuzzy on the perms needed for creating/updating releases.  Personally I'd do #98 and revert afterward, but it does clutter up the Git history.  Your call.

**Comment by cecton** [comment]
Fine by me. Sorry for all the work!

**Comment by bgilbert** [comment]
np!  Sorry for the extra hassle around the infra changes.

Those permissions worked, and I've copied the release notes into the release.  https://github.com/rust-disk-partition-management/gptman/pull/99 should be the last piece of cleanup.

**Comment by bgilbert** [comment]
(By the way, if I'm ever being too aggressive about maintenance in these repos, please do let me know.  My style may not match yours, and it's your project.)

**Comment by cecton** [comment]
(Ah thanks! This fine. Really I'm just happy we reduced bus factor and hopefully there won't be much maintenance in the future (if GH don't update their API because of security reasons too much :grin:))
